- name: Build Nodetool Node
  gather_facts: False
  hosts: localhost
  tasks:
    - name: Build Nodetool Node
      local_action:
        module: rax
        credentials: ~/.rackspace_cloud_credentials
        name: "nodetool-{{ item.value.region }}-%02d"
        exact_count: yes
        flavor: performance1-2
        image: ubuntu-1410-utopic-unicorn-pvhvm
        region: "{{ item.value.region }}"
        wait: yes
        state: absent
        group: nodetool
        count: "{{ item.value.node_count }}"
        files:
           /root/.ssh/authorized_keys: ~/.ssh/id_rsa.pub
        networks:
           - private
           - public
      with_dict: nodetool_opts
      register: rax
