- name: Build Nodetool Node
  gather_facts: False
  hosts: localhost
  tasks:
    - name: Build Nodetool Node
      local_action:
        module: rax
        credentials: ~/.rackspace_cloud_credentials
        name: "nodetool-{{ item.value.region }}-%02d"
        exact_count: yes
        flavor: performance1-2
        image: ubuntu-1410-utopic-unicorn-pvhvm
        region: "{{ item.value.region }}"
        wait: yes
        state: present
        group: nodetool
        count: "{{ item.value.node_count }}"
        files:
           /root/.ssh/authorized_keys: ~/.ssh/id_rsa.pub
        networks:
           - private
           - public
      with_dict: nodetool_opts
      register: rax

    - name: Add created servers to nodetool group
      local_action:
        module: add_host
        hostname: "{{ item.name }}"
        ansible_ssh_host: "{{ item.rax_accessipv4 }}"
        ansible_ssh_pass: "{{ item.rax_adminpass }} "
        groupname: nodetool
      with_items: rax.success
      when: rax.action =='create'
